[package]
name = "day04"
version = "0.1.0"
authors = ["Fredrik Fossum <fredrik.fossum@finn.no>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
digits_iterator = "0.1"
rayon = "1.2"
itertools = "0.8"
